#
# helix configuration for local development
#
version: 1

definitions:
  defaults:
    - &defaultRepo "ssh://git@github.com/moritzraho/trying-helix.git"

strains:
  - name: default
    code: ssh://git@github.com/moritzraho/trying-helix.git#master
    content: ssh://git@github.com/moritzraho/trying-helix.git#master
    static: ssh://git@github.com/moritzraho/trying-helix.git/htdocs#master
    package: mraho/dc63694136c84306e2407afb57d8d4473169df4b
